const A = "http://127.0.0.1:3107", B = "http://127.0.0.1:3108";
const KEY = "github_pat_11ALEXTEST000000000000_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ab";
let f = 0; const ok = (c, w, x) => (c ? console.log(`  ✓ ${w}`) : (f++, console.log(`  ✗ ${w} — ${JSON.stringify(x).slice(0, 300)}`)));
const call = async (b, p, body) => (await fetch(b + p, body ? { method: "POST", headers: { "content-type": "application/json", "x-repoboard": "1" }, body: JSON.stringify(body) } : {})).json();
console.log("Private code repository");
await call(A, "/api/repo", { token: KEY, repo: "lumen/browser" });
await call(A, "/api/docs?watch=1&force=1");
let r = await call(A, "/api/plan");
ok(r.status.codeVisibility === "private" && r.status.offer, "private, offer shown", r.status);
r = await call(A, "/api/plan", { action: "preview", to: { mode: "branch" } });
ok(!r.preview.problem && r.preview.toVisibility === "private", "the branch is private like the repository", r.preview);
r = await call(A, "/api/plan", { action: "move", to: { mode: "branch" }, leaveNote: true, removeOld: false });
ok(typeof r.copied === "number" && r.copied >= 9, `moved ${r.copied} files to the branch`, r);
await call(B, "/api/repo", { token: KEY, repo: "lumen/browser" });
r = await call(B, "/api/board", { action: "board-adopt" });
ok(r.plan?.location.mode === "branch", "B follows to the branch", r);
await call(B, "/api/docs?watch=1&force=1");
r = await call(B, "/api/docs");
ok(r.docs.length >= 9, `B reads ${r.docs.length} documents from the branch`, r);
r = await call(A, "/api/board", { action: "board-status" });
ok(r.autoSync && r.planMode === "branch", "boards sync on their own", r);
r = await call(A, "/api/board", { action: "sync-settings", autoSync: false });
ok(r.error?.includes("apart from main"), "turning automatic sync off is refused, with a reason", r);
console.log(f ? `${f} FAILED` : "all passed");
